#!/system/bin/sh

## Assumes busybox is installed
## For some reason, sensors need /system writeable on start, or
#  else the X-axis will be inverted

stop sensor-daemon
/system/xbin/mount -o remount,rw /system
start sensor-daemon
sleep 2;
/system/xbin/mount -o remount,ro /system
